# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setGeometry(QtCore.QRect(110, 50, 146, 106))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.username_label = QtWidgets.QLabel(self.splitter)
        self.username_label.setObjectName("username_label")
        self.login_field = QtWidgets.QLineEdit(self.splitter)
        self.login_field.setText("")
        self.login_field.setObjectName("login_field")
        self.pwd_label = QtWidgets.QLabel(self.splitter)
        self.pwd_label.setMinimumSize(QtCore.QSize(146, 16))
        self.pwd_label.setObjectName("pwd_label")
        self.password_field = QtWidgets.QLineEdit(self.splitter)
        self.password_field.setObjectName("password_field")
        self.Login_button = QtWidgets.QPushButton(self.splitter)
        self.Login_button.setObjectName("Login_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.username_label.setText(_translate("Form", "username"))
        self.pwd_label.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.pwd_label.setText(_translate("Form", "password"))
        self.Login_button.setText(_translate("Form", " Login or register"))
