# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'library_main_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LibraryMainPage(object):
    def setupUi(self, LibraryMainPage):
        LibraryMainPage.setObjectName("LibraryMainPage")
        LibraryMainPage.resize(640, 480)
        self.centralWidget = QtWidgets.QWidget(LibraryMainPage)
        self.centralWidget.setObjectName("centralWidget")
        self.search_lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.search_lineEdit.setGeometry(QtCore.QRect(20, 10, 300, 30))
        self.search_lineEdit.setObjectName("search_lineEdit")
        self.available_books_listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.available_books_listWidget.setGeometry(QtCore.QRect(20, 50, 300, 200))
        self.available_books_listWidget.setObjectName("available_books_listWidget")
        self.borrowed_books_listWidget = QtWidgets.QListWidget(self.centralWidget)
        self.borrowed_books_listWidget.setGeometry(QtCore.QRect(20, 260, 300, 200))
        self.borrowed_books_listWidget.setObjectName("borrowed_books_listWidget")
        self.user_profile_button = QtWidgets.QPushButton(self.centralWidget)
        self.user_profile_button.setGeometry(QtCore.QRect(330, 10, 100, 30))
        self.user_profile_button.setObjectName("user_profile_button")
        LibraryMainPage.setCentralWidget(self.centralWidget)

        self.retranslateUi(LibraryMainPage)
        QtCore.QMetaObject.connectSlotsByName(LibraryMainPage)

    def retranslateUi(self, LibraryMainPage):
        _translate = QtCore.QCoreApplication.translate
        LibraryMainPage.setWindowTitle(_translate("LibraryMainPage", "Library Main Page"))
        self.user_profile_button.setText(_translate("LibraryMainPage", "User Profile"))
